resolver: lts-20.24  # Compatible with GHC 9.2.8 and llvm-hs 15.0

extra-deps:
  - github: llvm-hs/llvm-hs
    commit: 5bca2c1a2a3aa98ecfb19181e7a5ebbf3e212b76
    subdirs:
      - llvm-hs
      - llvm-hs-pure

packages:
  - .

# GHC options for warnings and debugging
ghc-options:
  "$locals": -Wall -Wcompat -Widentities -Wredundant-constraints -Wtype-defaults
  "$everything": -O2

# Ensure LLVM compatibility
extra-include-dirs:
  - /usr/local/include
extra-lib-dirs:
  - /usr/local/lib

# Allow tests if any are included
allow-newer: true


